import { ClerkProvider } from '@clerk/nextjs';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Learn languages',
	description: 'Generated by create next app',
};

type RootLayoutProps = {
	children: ReactNode;
};

export const RootLayout = ({ children }: RootLayoutProps): ReactNode => {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${inter.className} bg-none bg-orange-400`}>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
};

export default RootLayout;
